### ISSUE TITLE
Great script

### ISSUE THREAD

**Issue by jjasghar** [sonata82/hubot-daily-comic#1]
I'd love to use this, but it seems this doesnt have the "standard" hubot package system.

https://github.com/hubot-scripts/hubot-example

Also if you could create an npm package we should easily add it to our `external-scripts.json` and leverage it :)

https://github.com/hubot-scripts/packages

https://gist.github.com/coolaj86/1318304

Thanks :+1:

**Comment by sonata82** [comment]
See https://www.npmjs.com/package/hubot-daily-comic.
